### ISSUE TITLE
Possible bug in lr.twosigma.R

### ISSUE THREAD

**Issue by chang-che** [edvanburen/twosigma#1]
Hi,
I think there is a potential bug in the lr.twosigma.R:
When there are only two covariates in mean_covar or zi_covar, the matrix reduces to vector once the contrast is dropped because there is only one column in the matrix.
https://github.com/edvanburen/twosigma/blob/29f1b6d55c1b9720f0afa1e44a5bc50a056bcff8/R/lr.twosigma.R#L140
https://github.com/edvanburen/twosigma/blob/29f1b6d55c1b9720f0afa1e44a5bc50a056bcff8/R/lr.twosigma.R#L152

Hence, it should be
'mean_covar<-mean_covar[,-index, drop = FALSE]
zi_covar<-zi_covar[,-index, drop = FALSE]`

Otherwise, the covariates will be set as constant in your following code.

**Comment by edvanburen** [comment]
Sorry for the late reply, but I very much appreciate you noticing this. I had tried to defensively anticipate this problem (i.e. separately handling matrix and vector inputs), but you are right.  Should be updated and fixed in the new GitHub version.
