### ISSUE TITLE
Adjusting for library size

### ISSUE THREAD

**Issue by ewynn610** [edvanburen/twosigma#4]
Hi Eric,

Thank you for developing this package. I am working on implementing it on some single cell data and have a quick question. Does your package include any mechanism to adjust for differences in library size between cells, for example, by including normalization factors as model offsets like they do in edgeR or DESeq2?

Thanks,

Elizabeth

**Comment by edvanburen** [comment]
Hello Elizabeth,

Thank you to you for using the package! The package does not have a default adjustment for library size, unfortunately.  I think the two options that are in the same vein are to: (1) use a normalization approach that produces integer normalized counts, and input them into twosigma or (2) include as a covariate something like the CDR (From the MAST paper) which is a surrogate for batch effects and, as I understand it, library size.  

Does this help?

Thanks,
Eric

**Comment by ewynn610** [comment]
Yes, that is helpful.

Thanks!
Elizabeth
